### ISSUE TITLE
Allow a maximum descr length hint

### ISSUE THREAD

**Issue by dmd** [jtebert/blurber#1]
I've added blurber to our irc bot: https://github.com/pgengler/GIR/pull/14  but the descriptions are really way too long for use in channel.

I'd like to be able to append something like /short or &length=nnn or something like that to the API request and get a default-shorter or custom-length blurb.

URGENT FOR LOL

**Comment by jtebert** [comment]
I've now added query parameters to the API for choosing the length and Markov chain depth for the description.

(Thanks for helping me procrastinate on studying.)
